version: '2.3'

volumes:
  local-storage:
    driver: local

networks:
  local:
    driver: bridge

services:

  dcc:
    image: "docker-cloud-compute:${VERSION}"
    ports:
      - "9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      #This volume is needed for running computes locally
      - local-storage:/app/local-storage
    command: ["node", "server/docker-cloud-compute-server.js"]
    depends_on:
      - redis
    environment:
      - PORT=9000
      - REDIS_HOST=redis
      - LOG_LEVEL=info
      - HOST_PWD=${PWD}
      - DISABLE_REQUEST_LOGS=true
    networks:
      - local

  # Run the functional and scaling tests in a separate container
  dcc.tests:
    image: "docker-cloud-compute:${VERSION}"
    working_dir: /app
    command: ["node",  "test/docker-cloud-compute-tester.js"]
    environment:
      - DCC=dcc:9000
      - LOG_LEVEL=debug
      - REDIS_HOST=redis
      - TRAVIS_REPO_SLUG=${TRAVIS_REPO_SLUG}
      - TEST=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - local
    depends_on:
      - redis
      - dcc

  redis:
    image: redis:3.2.0-alpine
    networks:
      - local
