version: '2'

volumes:
  redis-data:
    driver: local
  local-storage:
    driver: local

networks:
  dcc:
    driver: bridge

services:

  server:
    image: quay.io/bionano/docker-cloud-compute:dd574008
    cpu_shares: 1024
    ports:
      - "9090:9000"
    depends_on:
      - redis
    working_dir: /app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - local-storage:/app/local-storage
    environment:
      - PORT=9000
      - STORAGE_HTTP_PREFIX=http://ccc.local
      - REDIS_HOST=redis
      - LOG_LEVEL=info
    networks:
      - dcc

  redis:
    cpu_shares: 256
    image: redis:3.2.0-alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - dcc
    volumes:
      - ./etc/redis/redis-dev.conf:/usr/local/etc/redis/redis.conf
