version: '2'

volumes:
  local-storage:
    driver: local

networks:
  dcc:
    driver: bridge

services:

  dcc:
    image: "docker-cloud-compute:${VERSION}"
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      #This volume is needed for running computes locally
      - local-storage:/app/local-storage
    command: ["node", "server/docker-cloud-compute-server.js"]
    depends_on:
      - redis1
    environment:
      - PORT=9000
      # - STORAGE_HTTP_PREFIX=http://ccc.local
      - REDIS_HOST=redis1
      - LOG_LEVEL=info
      - HOST_PWD=${PWD}
    networks:
      - dcc

  # Run the functional and scaling tests in a separate container
  ccc.tests:
    image: "docker-cloud-compute:${VERSION}"
    working_dir: /app
    command: ["node",  "test/docker-cloud-compute-tester.js"]
    environment:
      - CCC=dcc
      - LOG_LEVEL=debug
      - REDIS_HOST=redis1
      - TRAVIS_REPO_SLUG=${TRAVIS_REPO_SLUG}
      - TEST=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - dcc
    depends_on:
      - redis1
      - dcc

  redis1:
    image: redis:3.2.0-alpine
    networks:
      - dcc
