version: '2.3'

volumes:
  local-storage:
    driver: local

networks:
  dcc:
    driver: bridge

services:

  server:
    depends_on:
      - redis
    working_dir: /app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - local-storage:/jobs
    environment:
      - PORT=9000
      - STORAGE_HTTP_PREFIX=http://dcc.local
      - REDIS_HOST=redis
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - WORKER_STATUS_CHECK_INTERVAL_SECONDS=3000
    networks:
      - dcc

  redis:
    image: redis:3.2.0-alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./etc/redis/redis-dev.conf:/usr/local/etc/redis/redis.conf
    networks:
      - dcc
    logging:
      driver: ${REDIS_LOG_DRIVER:-none}
