version: '2.3'

services:

  #Examine redis db
  redis-commander:
    cpu_shares: 256
    image: tenstartups/redis-commander
    command: --redis-host redis
    networks:
      - dcc
    depends_on:
      - redis
    ports:
      - "${PORT_REDIS_COMMANDER:-8081}:8081"
    logging:
        driver: none

  redis-bull:
    cpu_shares: 256
    image: mixmaxhq/arena
    volumes:
      - ./etc/redis/arena-index.json:/opt/arena/src/server/config/index.json
    depends_on:
      - redis
    ports:
      - "${PORT_REDIS_BULL:-4567}:4567"
    networks:
      - dcc
    logging:
        driver: none
