version: '2.3'

services:

  worker:
    image: dionjwa/haxe-watch:v0.15.0
    command: ["nodemon", "-L", "-w", "server", "server/docker-cloud-compute-server.js"]
    working_dir: /app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./build/server:/app/server
      - ./build/clients:/app/clients
      - ./src/web:/app/web
      - local-storage:/app/local-storage
      - ./package.json:/app/package.json
      - ./node_modules_docker:/app/node_modules
    environment:
      - PORT=9000
      - STORAGE_HTTP_PREFIX=http://dcc.local
      - REDIS_HOST=redis
      - LOG_LEVEL=info
      - FLUENT_HOST=fluentd
      - WORKER_STATUS_CHECK_INTERVAL_SECONDS=3000
    networks:
      - dcc
