version: '2'

volumes:
  redis-data:
    driver: local

services:

  ccc:
    image: "dionjwa/docker-cloud-compute:0.4.0"
    ports:
      - "9000:9000"
    links:
      - redis
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PORT=9000
      - STORAGE_HTTP_PREFIX=http://localhost:9000
      - REDIS_HOST=redis
      - LOG_LEVEL=debug
      - WORKER_STATUS_CHECK_INTERVAL_SECONDS=20

  redis:
    restart: always
    image: redis:3.2.0-alpine
    volumes:
      - redis-data:/data
